### ISSUE TITLE
upx_unpack.py error

### ISSUE THREAD

**Issue by Mafhoom** [fireeye/speakeasy#106]
Thank you for your creative thinking
I have an exe  UPX last version file,
I test your code and it can not handle it, Do you have any suggestion

C:\Python\>upx_unpack.py -f 1.exe -o 2.exe
[*] Unpacking module with section hop
Traceback (most recent call last):
  File "C:\Python\upx_unpack.py", line 67, in <module>
    main(args)
  File "C:\Python\upx_unpack.py", line 48, in main
    start = base + upx0.VirtualAddress
AttributeError: 'NoneType' object has no attribute 'VirtualAddress'

**Comment by jtbennett-fe** [comment]
Hello @Mafhoom , are you sure your PE has a section named 'UPX0'? Here is the code that is trying to find that section: https://github.com/fireeye/speakeasy/blob/master/examples/upx_unpack.py#L46

**Comment by Mafhoom** [comment]
I am noob but I opened it by PE-bear :

![image](https://user-images.githubusercontent.com/21289084/100998709-1c75f080-3571-11eb-9a77-2089872f4743.png)
Please help me.

**Comment by jtbennett-fe** [comment]
This is not a standard UPX-packed sample. The first two sections do not have names and standard UPX-packed samples have sections with the names "UPX0" and "UPX1".

**Comment by Mafhoom** [comment]
thank you for reply
I changed the section names:

import pefile

exe_path = "1.exe"
pe = pefile.PE(exe_path)


# Edit values
pe.sections[0].Name = "UPX0".encode()
pe.sections[1].Name = "UPX1".encode()

# Save the change in another executable
new_exe_path = r"2.exe"
pe.write(new_exe_path)

# Check the values
new_pe = pefile.PE(new_exe_path)
print("[*] New Section name = %s" % new_pe.sections[0].Name.decode('utf-8'))
print("[*] New Section name = %s" % new_pe.sections[0].Name.decode('utf-8'))

Now I have 2.exe with UPX sections name:
![image](https://user-images.githubusercontent.com/21289084/101174457-27a44b80-3659-11eb-887d-fa8bf9861dbf.png)

2.exe is ok and can run without problem

Again I used this command:

python.exe upx_unpack.py -f 2.exe -o 3.exe

It Shoed :
[*] Unpacking module with section hop

After some minutes it exited without any error but there is no 3.exe 
It could not generate 3.exe without any message!

**Comment by jtbennett-fe** [comment]
Sorry @Mafhoom , what I meant by my previous comment is that the upx_unpack.py example is only designed to work with standard UPX-packed executables. It is likely that the sample you are testing with is not using standard UPX, but either a modified UPX or something else entirely. Check out the [UPX website](https://upx.github.io/) to learn how to use UPX to pack an executable yourself and try our script with that sample. Good luck!
