### ISSUE TITLE
IoCreateDevice doesn't allocate memory for DeviceExtension

### ISSUE THREAD

**Issue by tarterp** [fireeye/speakeasy#127]
When calling IoCreateDevice with a DeviceExtension size specified the memory isn't being allocated for the extension.

```
status = IoCreateDevice(
             DriverObject,
             sizeof(DeviceExtension),
             0i64,
             FILE_DEVICE_UNKNOWN,
             FILE_DEVICE_SECURE_OPEN,
             0,
             &DeviceObject);
  if ( status >= 0 )
  {
    DeviceExtension = (DeviceExtension *)DeviceObject->DeviceExtension;
    ExInitializeFastMutex(&DeviceExtension->lock);
```

```
"error": {
                "type": "invalid_write",
                "pc": "0x140004cc2",
                "address": "0x8",
                "instr": "mov dword ptr [rax], ecx",
```

**Comment by tarterp** [comment]
Looking at code in kernel.py. The memory is allocated and a pointer to the extension is assigned to dev.object.DeviceObjectExtension.

**Comment by drewvis** [comment]
Fixed with https://github.com/fireeye/speakeasy/commit/0fdb1848196497c4accf8e26b828bce02cd621e6. We needed to set DeviceExtension. DeviceObjectExtension is an opaque field.
