### ISSUE TITLE
Relax unicorn requirements from 1.0.2rc4 to 1.0.2?

### ISSUE THREAD

**Issue by lennyzeltser** [fireeye/speakeasy#130]
The requirements.txt specifies that the required version of unicorn is 1.0.2rc4. However, the latest unicorn version is 1.0.2 (it's no longer a release candidate). As a result, running speakeasy produces an error:

```
$ emu_exe.py -f file.exe
....
....
AssertionError: Requires unicorn version: 1.0.2rc4
```
Would you consider relaxing the requirements to support unicorn 1.0.2 or higher?

**Comment by drewvis** [comment]
Agreed, doing some quick testing and I'll update.

**Comment by drewvis** [comment]
Updated: https://github.com/fireeye/speakeasy/commit/00c7ea448e924b2ddc792a0391d106a3ab354953

**Comment by lennyzeltser** [comment]
@drewvis, this issue is back, just for a different Unicorn version. I filed it here:
https://github.com/fireeye/speakeasy/issues/170

**Comment by drewvis** [comment]
Ah, maybe it makes sense to just remove this check entirely. I'll take a look this evening and push a fix. Thanks for the heads up.
