### ISSUE TITLE
TypeError in create_file_archive

### ISSUE THREAD

**Issue by re-fox** [fireeye/speakeasy#138]
Working on a small speakeasy loader, I hit a bug when trying to dump files.

```bash
  File "speakeasy_loader.py", line 52, in emulate_binary
    data = se.create_file_archive()
  File "speakeasy/speakeasy.py", line 612, in create_file_archive
    zf.writestr(file_name, f.get_data())
  File "/usr/lib64/python3.9/zipfile.py", line 1800, in writestr
    zinfo.file_size = len(data)            # Uncompressed size
TypeError: object of type 'NoneType' has no len()
```

Looks like `f.get_data()` is returning a `None` and zipfile is running a `len()` on it.  Triggering the error.  This could probably be patched out by having `get_data()` return a `b''`

The file used for testing was `23d263b6f55ac81f64c3c3cf628dd169d745e0f2b264581305f2f46efc879587` and the (relevant) code is 
```python
se = Speakeasy()
module = se.load_module(filename)
se.run_module(module, all_entrypoints=True)
data = se.create_file_archive()
with open('files.zip', 'wb') as fp:
    fp.write(data)
```

**Comment by drewvis** [comment]
This should be resolved with: https://github.com/fireeye/speakeasy/commit/d1e765438a978cdda849147f42ff1dc2201f9021.
