### ISSUE TITLE
Execute sample with administrator privilege

### ISSUE THREAD

**Issue by 0ssigeno** [fireeye/speakeasy#147]
Hi there!
Does Speakeasy support the possibility to execute the sample with administrator privilege?
A lot of samples change their execution based on that privilege, so I thought was a good "mode" allowed in the Profile definition.

**Comment by drewvis** [comment]
Hello,

Yep, it supports this. Check out: https://github.com/fireeye/speakeasy/blob/master/speakeasy/configs/default.json#L48. If the user in the profile has "is_admin" set to true, all APIs that query administrator status will report accordingly.

**Comment by 0ssigeno** [comment]
Thank you! Didn't see when I checked the examples
