### ISSUE TITLE
Requires unicorn version: 1.0.2. Relax this requirement?

### ISSUE THREAD

**Issue by lennyzeltser** [fireeye/speakeasy#170]
At the moment Speakeasy requires a very specific version of Unicorn: 1.0.2. However, the latest Unicorn version presently available via PyPI is 1.0.3. As a result, run_speakeasy.py produces an error:

```
AssertionError: Requires unicorn version: 1.0.2
```
Would it be possible to relax the Unicorn requirement so that 1.0.2 is the _lowest_ supported version, so that higher Unicorn versions would also be accepted?

**Comment by drewvis** [comment]
The assertion is removed with: https://github.com/fireeye/speakeasy/commit/9c6145e82a6b3c728ff902c88b2740b7f4fc1747
